@core_api_HostAddress = http://localhost:5000

GET {{core_api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{core_api_HostAddress}}/game/start


### 
GET {{core_api_HostAddress}}/game/resume/1fae893f-41a8-47e7-9ce6-a206cd31da93