name: Generate Daily Challenges

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 15 * * 0'  # sundays at 3PM

jobs:
  generate-challenges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}  
          API_URL: ${{ secrets.API_URL }}        
          COVERAGE: 1                            
        run: python src/scripts/plan-next-dailies.py