name: Generate Daily Challenges

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 15 * * 0'  # sundays at 3PM

jobs:
  generate-challenges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          COVERAGE: 10                            
        run: python src/scripts/plan-next-dailies.py ${{ secrets.AUTH_TOKEN }} ${{ secrets.API_URL }}  