name: Frontend - Build & tests

on:
  push: # push on master with changes in this file or in frontend folder
    branches: [ "master" ]
    paths:
    - '.github/workflows/test-frontend.yml'
    - 'src/frontend-web/**'
  pull_request: # all PR targeting master
    branches: [ "master" ]
  workflow_dispatch: # enable manual execution
  release:
    types: [published]  # When a new release is published

jobs:
  unit-and-build:
    name: Test and TypeScript Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend-web/monhundle-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./src/frontend-web/monhundle-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run TypeScript check
        run: npm run type-check

      - name: Run unit tests
        run: npm run test:unit

      - name: Build for production
        run: npm run build

  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend-web/monhundle-web

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./src/frontend-web/monhundle-web/package-lock.json

      - name: Install deps, build & warm Cypress cache
        uses: cypress-io/github-action@v7
        with:
          working-directory: ./src/frontend-web/monhundle-web
          build: npm run build
          runTests: false   # installe + build, ne lance pas encore les tests

      - name: Start preview server
        run: npx vite preview --port 4173 &

      - name: Wait for server
        run: npx wait-on http://localhost:4173

      - name: Run Cypress on all browsers # run each browser sequentially
        run: |
          STATUS=0
          for b in electron chrome firefox; do
            npx cypress run --browser $b || STATUS=1
          done
          exit $STATUS

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: cypress-screenshots
          path: ./src/frontend-web/monhundle-web/cypress/screenshots